project:
  type: website
  output-dir: docs
  
preview: 
  browser: true 
  watch-inputs: true
  navigate: true

website:
  title: Allison Koh

  back-to-top-navigation: true

  navbar:
    left:
      - href: index.qmd
        text: About
      - href: bio.qmd
        text: Bio
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: resources.qmd
        text: Resources
      - href: now.qmd
        text: Now
        
    right: 
      - icon: envelope
        aria-label: email
        href: "mailto:a.w.koh@bham.ac.uk"
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/allisonwkoh
        rel: me
      - icon: github
        aria-label: github
        href: https://github.com/allisonkoh
        rel: me
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/allisonkoh/
        rel: me

  page-footer:
    center: "[{{< fa brands creative-commons >}}](https://creativecommons.org/licenses/by/4.0/) Allison Koh 2024 • Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)" 
    
format:
  html:
    theme:
      dark: [vapor, theme_variables_dark.scss]
      light: [cerulean, theme_variables_light.scss]
    css: styles.css
    toc: true

editor: source

