project:
  type: website
  output-dir: docs
  
preview: 
  browser: true 
  watch-inputs: true
  navigate: true

website:
  title: Dr. Allison Koh
  favicon: sdv_portrait_logo.png
  
  google-analytics: "G-GXQP8QQQSR"

  back-to-top-navigation: true
  navbar:
    title: false
    logo: logo.svg
    search: true
    right:
    # left:
      # - href: index.qmd
      #   text: Home
      - text: About
        menu: 
        - href: bio.qmd
          text: Bio
        - text: CV
          href: files/Koh_CV.pdf
          target: _blank
        - href: now.qmd
          text: Now
      - text: Research
        menu:
        - href: research.qmd
          text: Publications 
      - text: Teaching
        menu: 
          - href: teaching.qmd
            text: Overview
          - href: sswpm.qmd
            text: Summer School for Women in Political Methodology
      - text: Resources 
        menu:
        - href: resources.qmd
          text: Overview
        - href: resources_python.qmd
          text: Python
        - href: resources_quarto.qmd
          text: Quarto
        - href: resources_r.qmd
          text: R
        - href: resources_other.qmd
          text: Other <br>
      - text: Contact
        menu: 
        - text: Email
          href: "mailto:a.w.koh@bham.ac.uk"
        - text: Twitter
          href: https://twitter.com/allisonwkoh
          rel: me
        - text: LinkedIn
          href: https://www.linkedin.com/in/allisonkoh/
          rel: me


  page-footer:
    border: false
    left: "[{{< fa brands creative-commons >}}](https://creativecommons.org/licenses/by/4.0/) Allison Koh 2025 • Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)"
    right:
    - icon: envelope
      aria-label: email
      href: "mailto:a.w.koh@bham.ac.uk"
    - icon: twitter
      aria-label: twitter
      href: https://twitter.com/allisonwkoh
      rel: me
    - icon: github
      aria-label: github
      href: https://github.com/allisonkoh
      rel: me
    - icon: linkedin
      aria-label: linkedin
      href: https://www.linkedin.com/in/allisonkoh/
      rel: me
    
format:
  html:
    theme:
      dark: [vapor, theme_variables_dark.scss]
      light: [cerulean, theme_variables_light.scss]
    css: styles.css
    toc: false
    page-layout: full

editor: source

