---
title: "Bio" 
subtitle: "Updated: July 13, 2024"
format: 
  html: 
    page-layout: full
    grid: 
      sidebar-width: 800px
---

Allison Koh is a Research Fellow in Natural Language Processing at the University of Birmingham’s Centre for Artificial Intelligence in Government. She is a computational political scientist working at the intersection of international relations, political communication, and computational methods. The substantive foci of her work are the geopolitics of emerging technologies and applications of generative AI in conflict research. Her ongoing research examines the strategic landscape of digital transnational repression on social media, the state-aligned online harassment of diaspora activists, and the effect of Twitter's recent policy changes on the influence of government and state-affiliated media accounts. Koh holds a PhD in Political Science and MPP in Policy Analysis from the Hertie School in Berlin, and completed her BSc in Economics and Asian Studies at Tulane University. 

Click [here](img/allisonkoh.png) for a high-quality headshot.   