---
title: "Now^[https://nownownow.com/about]"
---

As of June 15, 2026, this is what I'm up to: 

- I currently live in London 🇬🇧. It's no NYC, but it's a close second! 
- I am a Research Fellow (postdoc) in Natural Language Processing at the University of Birmingham's [Centre for Artificial Intelligence in Government](https://www.birmingham.ac.uk/research/centre-for-artificial-intelligence-in-government). I mostly work remotely from London, but commute to Birmingham 1-2 times per month. 
- Now that I'm out of the PhD-to-postdoc transition phase, I'm making moves on this massive backlog of papers I've developed over the past few years. If you're interested in what these papers are about, or if you are in some way otherwise invested in seeing my work thrive, please ask me about my publications-in-progress! I need an extra nudge on this one... 
- True to my roots as a former Tumblr/MySpace kid, I enjoy teaching myself how to code by breaking and debugging a variety of personal side quests (including this website). I am very intentional on making sure that coding agents don't interfere with this process that makes me a better researcher and a more fulfilled person. I'd be more than happy to teach others to do the same :) (both on the coding and not being jaded over AI coding agents)
- I've been traveling a lot lately. Hopefully things will start slowing down this fall. Here's where you'll find me in the coming months; please text/email me to meet up if we might be crossing paths: 
    - June: I'll be in Belfast for the first [European Political Science Society]() conference, where I'll be presenting my work on the "publicness" of politics on TikTok, convening (for the second time) a workshop on career development for PhDs/postdocs/the people that manage them, and taking part in another roundtable on the integration of AI in the social sciences. I may or may not be procrastinating my prep for all of these things through updating my now page. 
    - July: I'll be hopping around somewhere between Germany, Switzerland and France for travel to/from friends' weddings.
    - August: I'll be staying put in the UK for a much-needed break from international travel. 
- You can otherwise find me living by best city rat life in London at some pub/queer bar, art exhibition, or concert hall. If I'm not in any of those places, I'm probably at home playing videogames or hitting PRs at my local gym's Olympic weightlifting or strength training sessions. 
- Here's some of media that I'm engaging with/consuming: 
  - I'm currently playing Horizon Forbidden West on the PS5. It's easily become one of my favorite games. If you ask me about it IRL I will probably blab on about it for a _while_. 
  - I'm currently watching Love Island USA and Daria. I recently finished watching the Testaments, and am looking forward to watching the next season of I Kissed A Girl when it's released in a couple weeks. 
  - The algorithmic overlords of social media are feeding me disturbing AI fruit videos that all share the same annoying saxophone soundtrack in the background, hot takes on my favorite TV shows, and vivid hair content.  
<!-- - When I'm not outside, I am probably playing some sort of action-adventure game on the PS5 (currently Watchdogs Legion) or watching the trashiest and/or most competitive reality TV shows you can think of. My current favorite is Survivor.  -->