---
title: "Research"
subtitle: "Updated August 11, 2025"
format: 
  html: 
    page-layout: full
    grid: 
      sidebar-width: 750px

---

## Dissertation

*Platformed Power Plays: Authoritarian Adaptations in Foreign Social Media Spaces*

This dissertation investigated how vulnerabilities in social media companies’ transparency and content moderation policies can benefit the foreign policy interests of authoritarian regimes. It comprises of the three papers listed in the "Research in Progress" section below. 

## Publications

### Confererence Proceedings

**Koh, Allison**, Daniel Boey, and Hannah Béchara. 2021. ["Predicting Policy Domains from Party Manifestos with BERT and Convolutional Neural Networks".](https://osf.io/preprints/socarxiv/fjh4q/) In *Proceedings of the 1st Workshop on Computational Linguistics for Political Text Analysis*, Düsseldorf, Germany.

### Book Chapters 

Gohdes, Anita, **Allison Koh**, and Maurice Schumann. “Digital Authoritarianism”. Forthcoming 2025 in
the _De Gruyter Handbook of Political Control_, edited by Jessica Braithwaite and Jennifer Earl.

### Research in Progress

**Koh, Allison** and Joshua A. Tucker. *Transnational Repression at the Margins of Platform Governance: Inequalities in Online Engagement with Uyghur Dissidents*.

**Koh, Allison**. *Digital Transnational Repression in a Distinct Domain: Global Platforms as Arenas of Political Control*.

**Koh, Allison**. *Did Twitter's Removal of Government and State-Affiliated Media Labels Expand the Influence of State Actors?*. ([PAP](https://osf.io/4jxwt/))

### Outreach Publications

Ritholtz, Samuel, **Allison Koh**, and Anita R. Gohdes. ["Fanning the Flames of Hate: The Transnational Diffusion of Online Anti-LGBT+ Rhetoric and Offline Mobilisation"](https://gnet-research.org/2022/11/29/fanning-the-flames-of-hate-the-transnational-diffusion-of-online-anti-lgbt-rhetoric-and-offline-mobilisation-2/). *The Global Network on Extremism and Technology (GNET) - Gender and Online Extremism Series*, 29 Nov 2022.
