---
title: "Research"
---

```{r setup, include=FALSE}
# load dependencies 
library(tidyverse)
library(viridis)

# global options 
knitr::opts_chunk$set(echo = FALSE)
```

## Dissertation 

_Power Plays & Platform Politics: Authoritarian Adaptations in Cross-Border Digital Domains_ 

## Publications 

### Confererence Proceedings 

__Koh, Allison__, Daniel Boey, and Hannah Béchara. 2021. ["Predicting Policy Domains from Party Manifestos with BERT and Convolutional Neural Networks".](https://osf.io/preprints/socarxiv/fjh4q/) In _Proceedings of the 1st Workshop on Computational Linguistics for Political Text Analysis_, Düsseldorf, Germany.

### Research in Progress

__Koh, Allison__, Jonathan Nagler, and Joshua A. Tucker. _Nationalist Shields in Transnational Domains: PRC Supporters' Responses to Uyghur Activists-in-Exile on Twitter_. 

__Koh, Allison__. _Dealing with Diaspora Dissent in Different Domains: A Conceptual Framework of Authoritarian Regimes' Foreign Social Media Strategies_. 

__Koh, Allison__. _Did Twitter’s Removal of Government and State-Affiliated Media Labels Expand the Influence of State Actors?_. ([PAP]())

### Outreach Publications

Ritholtz, Samuel, __Allison Koh__, and Anita R. Gohdes. ["Fanning the Flames of Hate: The Transnational Diffusion of Online Anti-LGBT+ Rhetoric and Offline Mobilisation"](https://gnet-research.org/2022/11/29/fanning-the-flames-of-hate-the-transnational-diffusion-of-online-anti-lgbt-rhetoric-and-offline-mobilisation-2/). _The Global Network on Extremism and Technology (GNET) - Gender and Online Extremism Series_, 29 Nov 2022.  


