---
title: "Summer School for Women in Political Methodology: Day 1" 
subtitle: "_Updated August 11, 2025_"
format: 
  html: 
    page-layout: full
    grid: 
      sidebar-width: 800px
---

Hi SSWPM participants, 

It was great to meet you all! Here you can find all of the course materials for the short courses on <b>[Functional Programming in `R`](https://github.com/allisonkoh/workshop-functional-programming-r)</b> and <b>[Introduction to Python for `R` Users](https://github.com/allisonkoh/workshop-python-for-r-users)</b> that took place on July 21, 2025. 

__Preparation for both courses:__ Please have a short `R` data analysis script and/or structured data from your own work on hand. If we have time leftover after going through applied examples, we will use them to practice functional programming and Python "in the wild". 

## Functional Programming in `R`

### Course preparation 

This course was designed for participants with some baseline knowledge of R/RStudio and data management. If you would like a refresher on either of these things, feel free to peruse the following materials.

Please note that some of the information related to IDEs/the tidyverse may be a bit outdated. 

- [Introduction to `R`/RStudio](files/HertieDSWorkshop_Session1.pdf)
- [Data Management in `R`](files/HertieDSWorkshop_Session2.pdf)

### Course materials 

- [Slides](files/01_functional_programming_slides.html)
- Handout [[HTML](files/01_functional_programming_handout.html)] [[PDF](files/01_functional_programming_handout.pdf)]
- Handout with answers [[HTML](files/01_functional_programming_handout_with_answers.html)] [[PDF](files/01_functional_programming_handout_with_answers.pdf)]
- [R Project Folder](files/01_functional_programming.zip)
- [GitHub repository](https://github.com/allisonkoh/workshop-functional-programming-r)

## Introduction to Python for `R` users

### Course preparation 

We will be using [Google Colab](https://colab.research.google.com/) for this course. You don't need to do anything to set this up outside of having a Google account. 
 
For applied examples with data, we will be using the __Parties’ Immigration and Integration Positions Dataset (PImPo)__ (Lehmann and Zobel 2018). Please download the __PImPo Party-Level DS__ CSV file from here: [https://manifesto-project.wzb.eu/information/documents/pimpo](https://manifesto-project.wzb.eu/information/documents/pimpo). 

We will review how to load the dataset into Google Colab from your local files during the course.

### Course materials 

- [Handout](files/02_intro_python_handout.pdf)
- [Handout with answers](files/02_intro_python_handout_with_answers.pdf)
- [Colab notebook](https://colab.research.google.com/drive/1CBogWrGKMZIFolCrjtrFdKuhxYoHMYSs?usp=sharing)
- [Github repository](https://github.com/allisonkoh/workshop-python-for-r-users)

## References 

Lehmann, P., & Zobel, M.  (2018). Positions and saliency of immigration in party manifestos: A novel dataset using crowd coding. *European Journal of Political Research*, 57(4), 1056-1083. https://doi.org/10.1111/1475-6765.12295

