---
title: "Teaching"
subtitle: "I have taught a range of courses on data analysis and programming, with an emphasis on applied use cases for learners across disciplines and technical experience."
---

### University of Birmingham

- MSc Supervision, [AI and Sustainable Development ](https://www.birmingham.ac.uk/study/postgraduate/subjects/politics-development-and-international-relations-courses/ai-and-sustainable-development-msc) (2025)

### Summer School for Women in Political Methodology 

- Instructor for short courses on [Functional Programming in R](sswpm.html#functional-programming-in-r) and [Python for R Users](sswpm.html#introduction-to-python-for-r-users) (2025, University of Bremen)

### GESIS Fall Seminar in Computational Social Science

- Co-Instructor, Automated Web Data collection in R with Hauke Licht (2023)

### Berlin Graduate School for Global and Transregional Studies 

- Instructor, A Gentle Introduction to R and RStudio (2023)

### Hertie School

- Co-Instructor, A Gentle Introduction to LaTeX (2021)
- Research consultant on statistical computing in R and Python (2019-2021)
- TA, Data Science Workshop Series with Therese Anders and Will Lowe (2020) 
